version: '3'

services:
  registry:
    build:
      context: ..
      dockerfile: docker/registry.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_PORT=8080
    restart: unless-stopped

  inference:
    build:
      context: ..
      dockerfile: docker/inference.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/models/model.gguf
      - PORT=8000
      - REGISTRY_URL=http://registry:8080
    volumes:
      - ../models:/models
    depends_on:
      - registry
    restart: unless-stopped
