from client.api import Client

def main():
    # Create a client
    client = Client(
        registry_url="http://localhost:8080",
        model="deepseek-33b"  # Specify the model you want to use
    )
    
    # Generate text
    response = client.generate(
        prompt="What is LlamaNet?",
        max_tokens=150,
        temperature=0.7
    )
    
    if response:
        print(f"Generated by node {response.node_id}:")
        print(response.text)
        print(f"Generated {response.tokens_generated} tokens in {response.generation_time:.2f} seconds")
    else:
        print("Failed to generate text")

if __name__ == "__main__":
    main()
