import asyncio
from client.api import Client

async def main():
    # Create a client with bootstrap nodes
    client = Client(
        bootstrap_nodes="localhost:8001",  # Connect to bootstrap node
        model="deepseek-33b"  # Specify the model you want to use
    )
    
    try:
        # Generate text
        response = await client.generate(
            prompt="What is LlamaNet?",
            max_tokens=150,
            temperature=0.7
        )
        
        if response:
            print(f"Generated by node {response.node_id}:")
            print(response.text)
            print(f"Generated {response.tokens_generated} tokens in {response.generation_time:.2f} seconds")
        else:
            print("Failed to generate text")
    finally:
        await client.close()

if __name__ == "__main__":
    asyncio.run(main())
